apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mauroconraspipelinesdotnetcoredocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mauroconraspipelinesdotnetcoredocker 
    spec:
      containers:
        - name: mauroconraspipelinesdotnetcoredocker 
          image: msaitoursclacrlive.azurecr.io/mauroconraspipelinesdotnetcoredocker
          ports:
          - containerPort: 80